version: '3'

services:
  corpsystem_backend:
    container_name: corpsystem_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - envs/test.env
    command: ["/bin/bash", "-c",  "python manage.py runserver 0.0.0.0:8000"]